name: flash-cards.htsuyoshiy.online

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Vite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Enter directory
        run: cd flashcards

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: Upload to S3
        env:
          AWS_EC2_METADATA_DISABLED: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync ./dist/ s3://${{ secrets.AWS_S3_BUCKET }} --delete --exclude="*.md" --exclude="Dockerfile" --exclude="Makefile" --exclude=".git"
